Web/Controllers/BannerController.cs
using Entities.Models;
using Repository;
using Service.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    [Authorize]
    public class BannerController : Controller
    {
        private ProjectDbContext db = new ProjectDbContext();
        // GET: Banner
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(VmBanner model)
        {
            TempData["SuccessMsg"] = "";
            TempData["FailedMsg"] = "";
            if (ModelState.IsValid)
            {
                #region Image
                var uri = Request.Url.Host;
                System.IO.Directory.CreateDirectory(Server.MapPath("~/Images/Banner/" + uri));
                string path = "";
                if (model.BannerFile != null)
                {
                    string pic = System.IO.Path.GetFileName(model.BannerFile.FileName);
                    string physicalPath =
                        System.IO.Path.Combine(Server.MapPath("~/Images/Banner/" + uri), pic);
                    path = "/Images/Banner/" + uri + "/" + pic;
                    model.BannerFile.SaveAs(physicalPath);
                    model.BannerImgUrl = path;
                }
                #endregion
                var newdata = new Banner();
                    newdata.BannerHeaderId = model.BannerHeaderId;
                    newdata.BannerTitle = model.BannerTitle;
                    newdata.BannerDescription = model.BannerDescription;
                    newdata.BannerImgUrl = model.BannerImgUrl;
                    newdata.BannerTypeId = (int)BannerType.HomeSlider;
                    db.Banners.Add(newdata);
                    db.SaveChanges();
                    TempData["SuccessMsg"] = "Banner Added Successfully";
                    return RedirectToAction("Index");
            }
            else
            {
                TempData["FailedMsg"] = "Failed to Add Banner";
            }
            return View(model);
        }

        public ActionResult AjaxBanerList()
        {
            List<VmBanner> results = db.Banners.Where(a => a.Attribute5 != "false").Select(s => new VmBanner
            {
                BannerHeaderId = s.BannerHeaderId,
                BannerImgUrl = s.BannerImgUrl,
                BannerTitle = s.BannerTitle,
                BannerDescription = s.BannerDescription,
                BannerTypeId=s.BannerTypeId

            }).ToList();
            return Json(new
            {
                iTotalRecords = results.Count(),
                iTotalDisplayRecords = db.Banners.Count(),
                data = results
            },
            JsonRequestBehavior.AllowGet);

        }
    }
}

Web/Views/Banner/Add.cshtml
@model Service.ViewModels.VmBanner
@{
    ViewBag.Title = "Add Banner";
}

<div class="card-custom">
    <h4 class="text-center">Add Banner</h4>
    @using (Html.BeginForm("Add", "Banner", FormMethod.Post, new { @id = "mainForm", enctype = "multipart/form-data", @autocomplete = "off", onSubmit = "return ValidateFormData()" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row form-group">
            <div class="col-sm-4">
                <label>Banner Image</label>
                <input type="file" name="BannerFile" class="form-control" />
            </div>
            <div class="col-sm-8">
                <label>Title</label>
                @Html.TextBoxFor(model => model.BannerTitle, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BannerTitle, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row form-group">
            <div class="col-sm-12">
                <label>Description</label>
                @Html.TextAreaFor(model => model.BannerDescription, new { @class = "form-control", rows = "2" })
                @Html.ValidationMessageFor(model => model.BannerDescription, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="text-right">
            <button class="btn btn-success" type="submit">Submit</button>
        </div>
        <div class="clearfix"></div>
    }
</div>

Web/Views/Banner/Index.cshtml
@{
    ViewBag.Title = "Banners";
}

<h4 class="text-center">Banners</h4>
<div class="card-custom text-right">
    <a href="/Banner/Add">
        <button class="btn btn-primary mb-3" type="button">Add Banner</button>
    </a>
    <table id="bannerListTable" class="table table-hover text-center">
        <thead>
            <tr>
                <th>Seial No</th>
                <th>Image</th>
                <th>Title</th>
                <th>Description</th>
                <th>Action</th>
            </tr>
        </thead>
    </table>
</div>

@section scripts{
    <script src="https://cdn.datatables.net/plug-ins/1.10.19/api/fnPagingInfo.js"></script>
    <script>
        var oTable;
        var successMsg = '@TempData["SuccessMsg"]';
        var failedMsg = '@TempData["FailedMsg"]';
        $(document).ready(function () {
            if (successMsg != null && successMsg != "" && typeof successMsg != "undefined") {
                alert(successMsg);
            }
            if (failedMsg != null && failedMsg != "" && typeof failedMsg != "undefined") {
                alert(failedMsg);
            }
            oTable = $('#bannerListTable').DataTable({
                "lengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                "pageLength": 25,
                "processing": true,
                "serverSide": false,
                "ordering": false,
                "ajax": "/Banner/AjaxBanerList",
                "columns": [
                    { "data": "BannerHeaderId" },
                    {
                        "data": "Image",
                        "render": function (data, type, row, meta) {
                            return '<span class="table-img"><img src="' + row.BannerImgUrl + '"alt="" /></span>';

                        }
                    },
                    { "data": "BannerTitle" },
                    { "data": "BannerDescription" },
                    {
                        "render": function (data, type, row) {
                            return "<a href='/Banner/Delete/" + row.ProductHeaderId +"'><button type='button' class='btn btn-danger'>Delete</Button></a>";
                        }
                    }
                ],
                "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                    var page = this.fnPagingInfo().iPage;
                    var length = this.fnPagingInfo().iLength;
                    var index = (page * length + (iDisplayIndex + 1));
                    $('td:eq(0)', nRow).html(index);
                }
            });
        });
    </script>
}